version: "3"

services:
  db:
    image: postgres:alpine3.17
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: shopping-cart
      POSTGRES_PASSWORD: P@ssw0rd

  shopping-cart-backend:
    image: ghcr.io/baklanov-soft/shopping-cart-backend:master
    container_name: shopping-card-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_DB=shopping-cart
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=P@ssw0rd
      - DATABASE_MIGRATE=true
      - ADMIN_NAME=admin
      - ADMIN_PASSWORD=admin
