name: Tests on PRs

on:
  pull_request:
    branches: [ master ]

jobs:

  setup-jdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

  code-format:
    needs: setup-jdk
    steps:
      - name: Run scalafmt
        run: sbt scalafmtCheckAll

  unit-tests:
    needs: code-format
    steps:
      - name: Run tests
        run: sbt test

  integration-tests:
    needs: unit-tests
    steps:
      - name: Run integration tests
        run: sbt IntegrationTest/test