name: Tests on PRs

on:
  pull_request:
    branches: [ master ]

jobs:

  build-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run scalafmt
        run: sbt scalafmtCheckAll

      - name: Run tests
        run: sbt clean coverage test

      - name: Run integration tests
        run: sbt coverage it:test

      - name: Run coverage
        run: sbt coverageReport